### ISSUE TITLE
/Install.php does not work

### ISSUE THREAD

**Issue by TrueBooMShakalaka** [HFenter/MarginBot#12]
I follow the installation, no issues with creating tables, when I proceed with creating local user account with BFX keys it results the next page as error 500, when I after go to login I get the following:

```
Your Session Has Expired, Please Log In Again
×CloseIt appears you have not set up the hourly cron, or it hasn't been running. Check to make sure your cronjob contains a job similar to: 
5 * * * * wget -qO- http://XXX.XXX.XXX.XXX//crons/HourlyCron.php >/dev/null 2>&1
×CloseIt appears you have not set up the 10 minute cron, or it hasn't been running. Check to make sure your cronjob contains a job similar to:
01,11,21,31,41,51 * * * * wget -qO- http://XXX.XXX.XXX.XXX//crons/TenMinuteCron.php >/dev/null 2>&1
```

**Comment by HFenter** [comment]
After bitfinex was hacked, they closed down their API.  Since then they 
have reactivated it but with limited functionality, and from my 
understanding, some of the functions used by MarginBot are not working 
or changed.  It is possible that you can get it working, but I have not 
tried since the hack.

-Howard F.

**Comment by BeastOfBodmin** [comment]
What needs to exist in mysql before running the install script?

e.g. the schema user?

I've been beating my head against the installation for a few hours now. Cannot get past

Failed to connect to MySQL: (1044) Access denied for user 'myUser'@'localhost' to database 'mb_schema'
Please Fix Your Database Settings.

**Comment by HFenter** [comment]
The API is up and running again, and this issue should be fixed
