### ISSUE TITLE
I humbly submit a patch for README.md

### ISSUE THREAD

**Issue by BeastOfBodmin** [HFenter/MarginBot#16]
As I can't create branches/ pull requests, etc.

$ git diff README.md 
diff --git a/README.md b/README.md
index 2102095..475930b 100644
--- a/README.md
+++ b/README.md
@@ -43,6 +43,10 @@ If you don't have a bitfinex account, please consider using my [affiliate code](
 
 [https://www.bitfinex.com/?refcode=vsAnxuo5bM](https://www.bitfinex.com/?refcode=vsAnxuo5bM).
 
+## Project Development Thread on Bitointalk
+
+[MarginBot - A Bitfinex Margin Lending Management Bot](https://bitcointalk.org/index.php?topic=865250.msg9595391#msg9595391)
+
 ## Donations
 Developing this software, and testing the various strategies for lending that led to its development have taken significant time and effort.  If you find this software useful, please send a small donation our way.  All donations support the continued development of this software, and help to cover my distribution and support costs.

**Comment by HFenter** [comment]
It already has a link to the thread up higher, but I'm good with putting a clearer link to it down at the bottom.
