### ISSUE TITLE
Cancelled loans can take a while to show up in available funds

### ISSUE THREAD

**Issue by batterseapower** [HFenter/MarginBot#18]
This occasionally causes the bot to avoid offering some funds for loan until the next cron run.

I mostly fixed this by removing the use of `bitfinex_getDepositBalance` in `bitfinex_getMyLendRates` and instead hoisting it + a sleep to `bitfinex_updateMyLends`.

```
//  Step 1 - Cancel Pending Loans to return cash to available pool
//  this will loop through all currency types
$this->bitfinex_cancelPendingLoans();

// since we just canceled some loans we need to update this. Give a few secs to let the cancellations go through... seen delays in the past!
sleep(10);
$this->bitfinex_getDepositBalance();
```

**Comment by HFenter** [comment]
Hmm... this is already in the newest build.  Check the 1.07c update 
( https://github.com/HFenter/MarginBot/commit/faad48f67331084c566174b4464cd44cbdd0ae01#diff-fcf5969a2a6842b1b26b68e7442a2550 )

**Comment by HFenter** [comment]
If there is still an issue here let me know, otherwise I'll close this in a couple days.

**Comment by batterseapower** [comment]
Ah sorry - I didn't see that you'd already fixed this! Indeed I am running an old build.
